<a href="https://colab.research.google.com/github/tanisha1402/Machine-Learning-Practice/blob/main/9.Complete_Numpy_Tutorial_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy - Numerical pyhton

Advantages of Numpy :
1. allow sereval mathematical operations
2. faster operations

In [1]:
import numpy as np

# List Vs Numpy - Time Taken

In [2]:
from time import process_time

Time taken by a list

In [3]:
python_list =[i for i in range(500000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time= process_time()
print(end_time- start_time)

0.04946060799999996


Time Taken By a Numpy Array

In [4]:
nym_array = np.array([i for i in range(500000)])
start_time = process_time()
nym_array += 5
end_time = process_time()
print(end_time-start_time)

0.0006097229999999509


# Numpy Arrays

In [5]:
#list
l=[1,2,3,4,5]
print(l)
type(l)

[1, 2, 3, 4, 5]


list

In [6]:
# Numpy Array
a = np.array([1,2,3,4,5])
print(a)
type(a)

[1 2 3 4 5]


numpy.ndarray

In [7]:
# creating a 1 dimention array
ar = np.array([1,2,3,4,5])
print(ar)

[1 2 3 4 5]


In [8]:
a.shape # rows x cols

(5,)

In [9]:
b = np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
b.shape

(2, 3)

In [11]:
c = np.array([(1,2,3),(4,5,6)],dtype=float)
print(c)


[[1. 2. 3.]
 [4. 5. 6.]]


#  Initializing placeholders in np array

In [12]:
# creating a np array of zeros
z = np.zeros((5,4))
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
# creating a np array of ones
o = np.ones((4,5))
print(o)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
# creating a np array with a particular value
f = np.full((4,5),6)
print(f)

[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


In [15]:
# creating an identity matrix
i = np.eye(5)
print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
# creating a np array with random values
r = np.random.random((3,4))
print(r)

[[0.75556344 0.80889126 0.84320276 0.72046927]
 [0.36182924 0.94839115 0.73198937 0.57026323]
 [0.44206818 0.09797596 0.10956897 0.05117694]]


In [17]:
# random integer values within specific range
ri = np.random.randint(10,100,(5,6))
print(ri)

[[73 27 39 64 18 13]
 [51 83 17 25 99 27]
 [29 75 95 36 49 57]
 [85 48 88 62 50 91]
 [92 43 17 66 20 27]]


In [18]:
# array with even spaced values --> specifying the number of values required
r = np.linspace(10,20,7)
print(r)

[10.         11.66666667 13.33333333 15.         16.66666667 18.33333333
 20.        ]


In [19]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,20,5)
print(e)

[10 15]


In [20]:
# converting a list to a np array
l = [1,2,3,4,5]
print(l)
n_arr = np.asarray(l)
print(n_arr)
type(n_arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


numpy.ndarray

# Analyzing a np array

In [21]:
# Creation
n_arr = np.random.randint(10,100,(3,4))
print(n_arr)

[[74 78 81 12]
 [65 37 46 48]
 [85 14 43 18]]


In [22]:
print(n_arr.shape)

(3, 4)


In [23]:
print(n_arr.ndim)

2


In [24]:
print(n_arr.dtype)

int64


In [25]:
print(n_arr.size)

12


# Mathematical Operations For NP array

In [26]:
l1 = [1,2,3,4,5]
l2 = [5,4,3,2,1]
print(l1+l2) # it only concatenates , but doesn't perform addition on the values.

[1, 2, 3, 4, 5, 5, 4, 3, 2, 1]


In [27]:
a = np.random.randint(10,100,(3,4))
b = np.random.randint(10,100,(3,4))
print(a)
print(b)

[[71 16 55 90]
 [71 17 93 63]
 [53 19 13 17]]
[[25 69 76 29]
 [96 16 31 16]
 [58 20 99 95]]


In [28]:
# actually performs mathematical operations on the arrays
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 96  85 131 119]
 [167  33 124  79]
 [111  39 112 112]]
[[ 46 -53 -21  61]
 [-25   1  62  47]
 [ -5  -1 -86 -78]]
[[1775 1104 4180 2610]
 [6816  272 2883 1008]
 [3074  380 1287 1615]]
[[2.84       0.23188406 0.72368421 3.10344828]
 [0.73958333 1.0625     3.         3.9375    ]
 [0.9137931  0.95       0.13131313 0.17894737]]


In [29]:
# another way
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[ 96  85 131 119]
 [167  33 124  79]
 [111  39 112 112]]
[[ 46 -53 -21  61]
 [-25   1  62  47]
 [ -5  -1 -86 -78]]
[[1775 1104 4180 2610]
 [6816  272 2883 1008]
 [3074  380 1287 1615]]
[[2.84       0.23188406 0.72368421 3.10344828]
 [0.73958333 1.0625     3.         3.9375    ]
 [0.9137931  0.95       0.13131313 0.17894737]]


# Array Manipulation

In [30]:
a = np.random.randint(10,100,(3,4))
print(a)
print(a.shape)

[[32 28 10 25]
 [67 26 35 97]
 [30 12 94 15]]
(3, 4)


In [31]:
# transpose
t  = np.transpose(a)
print(t)
print(t.shape)

[[32 67 30]
 [28 26 12]
 [10 35 94]
 [25 97 15]]
(4, 3)


In [32]:
ab = np.random.randint(10,100,(3,4))
print(a)
print(a.shape)

[[32 28 10 25]
 [67 26 35 97]
 [30 12 94 15]]
(3, 4)


In [33]:
t1 = ab.T
print(t1)
print(t1.shape)


[[27 17 37]
 [28 70 73]
 [86 21 38]
 [55 14 79]]
(4, 3)


In [34]:
a = np.random.randint(10,100,(3,4))
print(a.shape)

(3, 4)


In [35]:
b = a.reshape(4,3)
print(b)
print(b.shape)

[[56 20 70]
 [63 27 99]
 [77 52 73]
 [13 19 49]]
(4, 3)
