<a href="https://colab.research.google.com/github/tanisha1402/Machine-Learning-Practice/blob/main/Extras/numpy_exercises_100_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Exercise 1
Solution:

In [ ]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Exercise 2
Solution:

In [ ]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### Exercise 3
Solution:

In [ ]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### Exercise 4
Solution:

In [ ]:
np.arange(50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### Exercise 5
Solution:

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Exercise 6
Solution:

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Exercise 7
Solution:

In [ ]:
np.random.random((3,3,3))

array([[[0.56301677, 0.73118761, 0.84296238],
        [0.26039865, 0.42043299, 0.73419025],
        [0.73826158, 0.69689849, 0.15080544]],

       [[0.06048835, 0.08410571, 0.10489956],
        [0.51390922, 0.40565991, 0.49498461],
        [0.68040304, 0.47864996, 0.56423621]],

       [[0.70904568, 0.72280067, 0.80009734],
        [0.70502537, 0.99810954, 0.29048011],
        [0.54902575, 0.48164164, 0.42533017]]])

### Exercise 8
Solution:

In [ ]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### Exercise 9
Solution:

In [ ]:
np.ones((10,10)); a = np.ones((10,10)); a[1:-1,1:-1]=0; a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### Exercise 10
Solution:

In [ ]:
np.arange(10,101,10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

### Exercise 11
Solution:

In [ ]:
a = np.arange(9).reshape(3,3)
a[1,1]

np.int64(4)

### Exercise 12
Solution:

In [ ]:
a = np.arange(9).reshape(3,3)
a[0:2,1:3]

array([[1, 2],
       [4, 5]])

### Exercise 13
Solution:

In [ ]:
a = np.arange(8)
a[[4,3,1,7]]

array([4, 3, 1, 7])

### Exercise 14
Solution:

In [ ]:
a = np.arange(10)
a[(a % 2) == 1]

array([1, 3, 5, 7, 9])

### Exercise 15
Solution:

In [ ]:
np.random.random(30).mean()

np.float64(0.4924455599054738)

### Exercise 16
Solution:

In [ ]:
np.ones(10).astype(int)
# or np.arange(10).astype(float)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Exercise 17
Solution:

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Exercise 18
Solution:

In [ ]:
a = np.arange(10); a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Exercise 19
Solution:

In [ ]:
a = np.arange(9).reshape(3,3)
a.sum(axis=0)

array([ 9, 12, 15])

### Exercise 20
Solution:

In [ ]:
a = np.arange(9).reshape(3,3)
a.sum(axis=1)

array([ 3, 12, 21])

### Exercise 21
Solution:

In [ ]:
a = np.arange(9); a.max(), a.min()

(np.int64(8), np.int64(0))

### Exercise 22
Solution:

In [ ]:
a = np.arange(10); a.mean()

np.float64(4.5)

### Exercise 23
Solution:

In [ ]:
a = np.arange(16).reshape(4,4); a.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36]])

### Exercise 24
Solution:

In [ ]:
a = np.arange(16).reshape(4,4); a.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38],
       [12, 25, 39, 54]])

### Exercise 25
Solution:

In [ ]:
a = np.random.randn(5); a.sort(); a

array([-1.69447107, -1.13207257, -0.88795224, -0.24671287,  0.39870911])

### Exercise 26
Solution:

In [ ]:
a = np.array([1,2,3,4,5]); np.where(a%2==0)[0]  # indices of even numbers

array([1, 3])

### Exercise 27
Solution:

In [ ]:
a = np.array([1,2,3,2,1]); np.unique(a)

array([1, 2, 3])

### Exercise 28
Solution:

In [ ]:
np.random.random((3,3))*10

array([[6.32903034, 1.57511013, 9.68830743],
       [5.65471495, 4.42587001, 9.41144307],
       [0.54248674, 7.60470489, 5.9681958 ]])

### Exercise 29
Solution:

In [ ]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Exercise 30
Solution:

In [ ]:
a = np.arange(12); a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Exercise 31
Solution:

In [ ]:
a = np.arange(36); a.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

### Exercise 32
Solution:

In [ ]:
a = np.arange(0,100); a[(a>50) & (a<80)]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

### Exercise 33
Solution:

In [ ]:
a = np.random.randint(0,10,10); np.unique(a, return_counts=True)

(array([1, 3, 4, 5, 6, 8], dtype=int32), array([1, 2, 2, 3, 1, 1]))

### Exercise 34
Solution:

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Exercise 35
Solution:

In [ ]:
a = np.arange(3); np.tile(a,3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

### Exercise 36
Solution:

In [ ]:
a = np.arange(6); a.reshape(2,3).T

array([[0, 3],
       [1, 4],
       [2, 5]])

### Exercise 37
Solution:

In [ ]:
a = np.arange(8).reshape(2,4); np.hstack((a,a))

array([[0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7]])

### Exercise 38
Solution:

In [ ]:
a = np.arange(8).reshape(2,4); np.vstack((a,a))

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

### Exercise 39
Solution:

In [ ]:
a = np.arange(9).reshape(3,3); np.diag(a)

array([0, 4, 8])

### Exercise 40
Solution:

In [ ]:
a = np.arange(9).reshape(3,3); np.diag(a, k=1)

array([1, 5])

### Exercise 41
Solution:

In [ ]:
a = np.arange(10); a[(a%3)==0]

array([0, 3, 6, 9])

### Exercise 42
Solution:

In [ ]:
a = np.random.random(10); a - a.mean()

array([-0.18774892, -0.13484898,  0.14015716,  0.30650869,  0.4367312 ,
       -0.41133083,  0.35485513, -0.3390818 ,  0.23124324, -0.39648489])

### Exercise 43
Solution:

In [ ]:
a = np.random.randint(0,10,10); np.bincount(a)

array([1, 0, 0, 1, 2, 1, 1, 0, 3, 1])

### Exercise 44
Solution:

In [ ]:
np.eye(3, k=1)  # identity with offset

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

### Exercise 45
Solution:

In [ ]:
a = np.arange(4); np.repeat(a,3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3])

### Exercise 46
Solution:

In [ ]:
a = np.arange(4); np.repeat(a, [1,2,3,4])

array([0, 1, 1, 2, 2, 2, 3, 3, 3, 3])

### Exercise 47
Solution:

In [ ]:
a = np.arange(10); np.intersect1d(a[:6], a[5:])

array([5])

### Exercise 48
Solution:

In [ ]:
a = np.arange(10); b = a.copy(); b[::2] = -1; np.where(b<0)[0]

array([0, 2, 4, 6, 8])

### Exercise 49
Solution:

In [ ]:
a = np.arange(25).reshape(5,5); a[::2, ::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

### Exercise 50
Solution:

In [ ]:
a = np.arange(25).reshape(5,5); a[:, 1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

### Exercise 51
Solution:

In [ ]:
a = np.arange(9); a.reshape(3,3); np.dot(np.eye(3), np.arange(3))

array([0., 1., 2.])

### Exercise 52
Solution:

In [ ]:
a = np.array([1,2,3]); b = np.array([4,5,6]); np.cross(a,b)

array([-3,  6, -3])

### Exercise 53
Solution:

In [ ]:
a = np.arange(16).reshape(4,4); np.linalg.det(a.astype(float))

np.float64(0.0)

### Exercise 54
Solution:

In [ ]:
a = np.array([1,2,3]); np.linalg.norm(a)

np.float64(3.7416573867739413)

### Exercise 55
Solution:

In [ ]:
a = np.random.randint(0,10,(3,3)); np.linalg.inv(a.astype(float))

array([[ 0.13953488, -0.06976744,  0.09302326],
       [-0.04651163,  0.02325581,  0.30232558],
       [-0.08527132,  0.20930233, -0.27906977]])

### Exercise 56
Solution:

In [ ]:
a = np.arange(10); np.save('arr.npy', a); loaded = np.load('arr.npy'); loaded

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Exercise 57
Solution:

In [ ]:
a = np.arange(10); np.savez('arrays.npz', a=a, b=a*2); np.load('arrays.npz')['b']

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Exercise 58
Solution:

In [ ]:
a = np.arange(12).reshape(3,4); np.argmax(a, axis=0)

array([2, 2, 2, 2])

### Exercise 59
Solution:

In [ ]:
a = np.arange(12).reshape(3,4); np.argmin(a, axis=1)

array([0, 0, 0])

### Exercise 60
Solution:

In [ ]:
a = np.array([1,2,3,4]); np.isfinite(a).all()

np.True_

### Exercise 61
Solution:

In [ ]:
a = np.array([1,2,3,4]); np.isin([2,3,10], a)

array([ True,  True, False])

### Exercise 62
Solution:

In [ ]:
a = np.random.randn(1000); (a - a.mean())/a.std()  # standardize

array([ 5.84220620e-02, -1.76804062e+00,  1.42256654e-01, -2.23360424e-01,
        3.35745018e-01, -2.77354210e-01,  2.01366599e+00,  2.11427791e+00,
        1.29784579e+00,  5.02578429e-01,  7.03995277e-02,  6.01159429e-01,
       -5.83969701e-01, -4.93912151e-01, -6.16685464e-01, -6.65287652e-01,
       -4.76405046e-01,  1.53989031e-01,  2.11754640e-01, -5.22114132e-01,
       -7.65731785e-01,  4.17788266e-01, -1.71950323e+00,  3.12452443e-01,
        4.74938202e-01,  1.33322052e-01, -2.58454935e-01,  1.52781807e+00,
       -1.71611960e+00,  1.77555319e+00, -3.72643882e-01, -1.04275859e+00,
        2.45008553e-02,  2.95800573e-01,  1.07703316e+00,  3.86834265e-01,
        4.36766263e-01,  1.19563420e+00, -1.03060847e+00,  7.54846154e-01,
        2.81129176e-01, -6.91419371e-01,  1.31031339e+00, -6.38506410e-01,
       -6.44149152e-02, -1.15791911e+00, -1.54116154e+00,  3.95563719e-03,
       -1.18394181e+00, -3.10359952e+00, -7.16739069e-01, -4.92613141e-01,
        7.37878971e-01,  

### Exercise 63
Solution:

In [ ]:
a = np.arange(10); np.add.accumulate(a)  # cumsum equivalent

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

### Exercise 64
Solution:

In [ ]:
a = np.arange(1,10); np.prod(a)

np.int64(362880)

### Exercise 65
Solution:

In [ ]:
a = np.arange(6).reshape(2,3); np.mean(a, axis=1)

array([1., 4.])

### Exercise 66
Solution:

In [ ]:
a = np.arange(12); a.reshape(3,4); np.swapaxes(a.reshape(3,4),0,1)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### Exercise 67
Solution:

In [ ]:
a = np.arange(8); a.reshape(2,4); a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

### Exercise 68
Solution:

In [ ]:
a = np.arange(9).reshape(3,3); a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### Exercise 69
Solution:

In [ ]:
a = np.arange(1,13).reshape(3,4); np.split(a, 3)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

### Exercise 70
Solution:

In [ ]:
a = np.arange(8).reshape(2,4); np.hsplit(a, 2)

[array([[0, 1],
        [4, 5]]),
 array([[2, 3],
        [6, 7]])]

### Exercise 71
Solution:

In [ ]:
a = np.arange(10); np.percentile(a, [25,50,75])

array([2.25, 4.5 , 6.75])

### Exercise 72
Solution:

In [ ]:
a = np.random.randint(0,5,10); np.sort(a)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4], dtype=int32)

### Exercise 73
Solution:

In [ ]:
a = np.arange(12).reshape(3,4); a.shape = (4,3); a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### Exercise 74
Solution:

In [ ]:
a = np.arange(12).reshape(3,4); a.astype(float)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

### Exercise 75
Solution:

In [ ]:
a = np.array([1,2,3,4]); b = np.array([5,6,7,8]); np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

### Exercise 76
Solution:

In [ ]:
a = np.arange(6).reshape(2,3); b = a.copy(); b[0,0] = 99; a, b  # show copy vs view

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[99,  1,  2],
        [ 3,  4,  5]]))

### Exercise 77
Solution:

In [ ]:
a = np.arange(16).reshape(4,4); a[~(a%2==0)]  # odd elements

array([ 1,  3,  5,  7,  9, 11, 13, 15])

### Exercise 78
Solution:

In [ ]:
a = np.random.randint(0,10,(5,)); np.bincount(a).argmax()  # most frequent

np.int64(0)

### Exercise 79
Solution:

In [ ]:
a = np.linspace(0,2*np.pi,100); np.sin(a)

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

### Exercise 80
Solution:

In [ ]:
a = np.arange(10); np.diff(a)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

### Exercise 81
Solution:

In [ ]:
a = np.array([1,2,3]); b = np.array([4,5,6]); np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

### Exercise 82
Solution:

In [ ]:
a = np.array([1,2,3]); b = np.array([4,5,6]); np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

### Exercise 83
Solution:

In [ ]:
a = np.arange(10); np.clip(a, 3, 7)

array([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

### Exercise 84
Solution:

In [ ]:
a = np.arange(12).reshape(3,4); a.sum()

np.int64(66)

### Exercise 85
Solution:

In [ ]:
a = np.arange(1,10); np.cumprod(a)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

### Exercise 86
Solution:

In [ ]:
a = np.array([1,2,3]); np.tile(a, (3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

### Exercise 87
Solution:

In [ ]:
a = np.array([1,2,3]); np.repeat(a, 2)

array([1, 1, 2, 2, 3, 3])

### Exercise 88
Solution:

In [ ]:
a = np.random.rand(5); np.argsort(a)

array([1, 2, 4, 3, 0])

### Exercise 89
Solution:

In [ ]:
a = np.arange(100).reshape(10,10); a[::2, ::3]

array([[ 0,  3,  6,  9],
       [20, 23, 26, 29],
       [40, 43, 46, 49],
       [60, 63, 66, 69],
       [80, 83, 86, 89]])

### Exercise 90
Solution:

In [ ]:
a = np.eye(3); np.trace(a)

np.float64(3.0)

### Exercise 91
Solution:

In [ ]:
a = np.arange(9).reshape(3,3); np.linalg.eig(a.astype(float))

EigResult(eigenvalues=array([ 1.33484692e+01, -1.34846923e+00, -2.48477279e-16]), eigenvectors=array([[ 0.16476382,  0.79969966,  0.40824829],
       [ 0.50577448,  0.10420579, -0.81649658],
       [ 0.84678513, -0.59128809,  0.40824829]]))

### Exercise 92
Solution:

In [ ]:
a = np.linspace(0,1,6); np.repeat(a, 2)[:len(a)]  # example reshaping via repeat

array([0. , 0. , 0.2, 0.2, 0.4, 0.4])

### Exercise 93
Solution:

In [ ]:
a = np.arange(10); np.savez_compressed('arrs.npz', a=a); np.load('arrs.npz')['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Exercise 94
Solution:

In [ ]:
a = np.arange(12).reshape(3,4); a[1] = a[1] * 10; a

array([[ 0,  1,  2,  3],
       [40, 50, 60, 70],
       [ 8,  9, 10, 11]])

### Exercise 95
Solution:

In [ ]:
a = np.arange(12).reshape(3,4); a.T.dot(a)

array([[ 80,  92, 104, 116],
       [ 92, 107, 122, 137],
       [104, 122, 140, 158],
       [116, 137, 158, 179]])

### Exercise 96
Solution:

In [ ]:
a = np.arange(5); np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

### Exercise 97
Solution:

In [ ]:
a = np.arange(5); np.log(a+1)  # avoid log(0)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

### Exercise 98
Solution:

In [ ]:
a = np.array([1,2,3]); b = np.array([0,1,0]); np.where(b, a, -a)

array([-1,  2, -3])

### Exercise 99
Solution:

In [ ]:
a = np.arange(6).reshape(2,3); np.apply_along_axis(lambda x: x*2, 1, a)

array([[ 0,  2,  4],
       [ 6,  8, 10]])

### Exercise 100
Solution:

In [ ]:
a = np.arange(12).reshape(3,4); np.savetxt('arr.txt', a, fmt='%d'); np.loadtxt('arr.txt', dtype=int)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])